version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/midware-single-spa

    steps:
      - checkout
      - attach_workspace:
          at: ~/midware-single-spa
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Build
          command: yarn build
      - run:
          name: Run Type Check
          command: yarn run tsc --noEmit
      - run:
          name: Run Tests
          command: yarn test --coverage
          no_output_timeout: 300m
      - run:
          name: Generate coverage
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Coveralls coverage
          command: ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
